name: Initial Tweet Deletion Setup

on:
  schedule:
    # Run once on March 24, 2025 at 00:00 UTC
    - cron: '0 0 24 3 *'
  workflow_dispatch:      # Allows manual trigger for testing

jobs:
  initial-setup:
    runs-on: ubuntu-latest
    
    env:
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      TWITTER_USER_ID: ${{ secrets.TWITTER_USER_ID }}
      # Flag to force initial retrieval
      OPERATION_MODE: 'initialize'

    steps:
    - name: Check if current year is 2025
      id: check_year
      run: |
        current_year=$(date +%Y)
        echo "Current year: $current_year"
        if [[ "$current_year" == "2025" || "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "should_run=true" >> $GITHUB_OUTPUT
        else
          echo "should_run=false" >> $GITHUB_OUTPUT
          echo "Skipping execution - not 2025 yet"
        fi

    - name: Checkout repository
      if: steps.check_year.outputs.should_run == 'true'
      uses: actions/checkout@v4

    - name: Set up Python
      if: steps.check_year.outputs.should_run == 'true'
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      if: steps.check_year.outputs.should_run == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install requests requests-oauthlib python-dotenv

    - name: Run initial tweet pull
      if: steps.check_year.outputs.should_run == 'true'
      id: run_script
      shell: bash
      run: |
        # Set PYTHONUNBUFFERED to show output in real-time in GitHub logs
        export PYTHONUNBUFFERED=1
        
        # Run the script and capture output
        python main.py 2>&1 | tee setup_output.log
        exit_code=${PIPESTATUS[0]}
        
        echo "exit_code=$exit_code" >> "$GITHUB_OUTPUT"
        
        # Display API responses in GitHub summary
        echo "## Initial Setup Summary" >> $GITHUB_STEP_SUMMARY
        echo "Process started on March 24, 2025 at 00:00 UTC" >> $GITHUB_STEP_SUMMARY
        grep "API call" setup_output.log >> $GITHUB_STEP_SUMMARY || echo "No API calls made" >> $GITHUB_STEP_SUMMARY
        
        exit $exit_code

    - name: Upload logs as artifact
      if: steps.check_year.outputs.should_run == 'true'
      uses: actions/upload-artifact@v3
      with:
        name: setup-logs
        path: |
          setup_output.log
          api_calls.log
        
    - name: Commit and push retrieved tweet IDs
      if: steps.check_year.outputs.should_run == 'true'
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add tweet_ids.json last_pull.txt || true
        git commit -m "Initial tweet ID retrieval (process start)" || true
        git push || true 