name: Tweet Deletion

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC daily
  workflow_dispatch:      # Allows manual trigger

jobs:
  delete-tweets:
    runs-on: ubuntu-latest
    
    env:
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-dev \
          build-essential \
          libffi-dev \
          libssl-dev

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools

    - name: Install aiohttp dependencies first
      run: |
        pip install \
          multidict \
          yarl \
          async-timeout \
          frozenlist \
          aiosignal \
          attrs \
          charset-normalizer

    - name: Install aiohttp
      run: |
        pip install aiohttp --no-deps

    - name: Install remaining dependencies
      run: |
        pip install -r requirements.txt --no-deps

    - name: Run tweet deletion script
      run: python main.py 