name: Tweet Deletion

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC daily
  workflow_dispatch:      # Allows manual trigger

jobs:
  delete-tweets:
    runs-on: ubuntu-latest
    
    env:
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-dev \
          build-essential \
          libffi-dev \
          libssl-dev

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools

    - name: Install core dependencies
      run: |
        pip install requests
        pip install requests-oauthlib
        pip install python-dotenv

    - name: Install aiohttp dependencies
      run: |
        pip install \
          multidict \
          yarl \
          async-timeout \
          frozenlist \
          aiosignal \
          attrs \
          charset-normalizer

    - name: Install aiohttp
      run: |
        pip install aiohttp --no-deps

    - name: Run tweet deletion script
      id: run_script
      shell: bash
      run: |
        python main.py
        STATUS=$?
        echo "status=$STATUS" >> $GITHUB_OUTPUT

    - name: Handle script exit code
      if: always()
      shell: bash
      run: |
        STATUS=${{ steps.run_script.outputs.status }}
        echo "Script exit code: $STATUS"
        
        if [ -z "$STATUS" ]; then
          echo "Error: Exit code is empty"
          exit 1
        fi
        
        case $STATUS in
          0)
            echo "Success: Script completed normally"
            exit 0
            ;;
          2)
            echo "Monthly cap reached. Scheduling next run for the start of next month."
            gh workflow run tweet-deletion.yml --ref ${{ github.ref }} --schedule "0 0 1 * *"
            exit 0
            ;;
          3)
            echo "Rate limit reached. Scheduling next run in 15 minutes."
            gh workflow run tweet-deletion.yml --ref ${{ github.ref }} --schedule "*/15 * * * *"
            exit 0
            ;;
          429)
            echo "Too Many Requests (429). Waiting for rate limit reset."
            gh workflow run tweet-deletion.yml --ref ${{ github.ref }} --schedule "*/15 * * * *"
            exit 0
            ;;
          *)
            echo "Unknown error occurred (Exit code: $STATUS)"
            exit 1
            ;;
        esac
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 