name: Tweet Deletion

on:
  schedule:
    # Run daily at 3:00 UTC to delete tweets (using stored IDs)
    - cron: '0 3 * * *'  # At 3:00 UTC every day
  workflow_dispatch:      # Allows manual trigger

jobs:
  delete-tweets:
    runs-on: ubuntu-latest
    
    env:
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      TWITTER_USER_ID: ${{ secrets.TWITTER_USER_ID }}
      # Flag to indicate this is a deletion-only run
      OPERATION_MODE: 'delete'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests requests-oauthlib python-dotenv

    - name: Run tweet deletion script
      id: run_script
      shell: bash
      run: |
        # Set PYTHONUNBUFFERED to show output in real-time in GitHub logs
        export PYTHONUNBUFFERED=1
        
        # Run the script and capture output
        python main.py 2>&1 | tee deletion_output.log
        exit_code=${PIPESTATUS[0]}
        
        echo "exit_code=$exit_code" >> "$GITHUB_OUTPUT"
        
        # Display API responses in GitHub summary
        echo "## X API Response Summary" >> $GITHUB_STEP_SUMMARY
        grep "API call" deletion_output.log >> $GITHUB_STEP_SUMMARY || echo "No API calls made" >> $GITHUB_STEP_SUMMARY
        
        # Display rate limit info
        echo "## Rate Limit Information" >> $GITHUB_STEP_SUMMARY
        grep "rate limit" deletion_output.log >> $GITHUB_STEP_SUMMARY || echo "No rate limit information" >> $GITHUB_STEP_SUMMARY
        
        # Display tweet deletion summary
        echo "## Tweet Deletion Summary" >> $GITHUB_STEP_SUMMARY
        grep "Deleted tweet" deletion_output.log >> $GITHUB_STEP_SUMMARY || echo "No tweets deleted" >> $GITHUB_STEP_SUMMARY
        
        exit $exit_code

    - name: Upload logs as artifact
      uses: actions/upload-artifact@v4
      with:
        name: deletion-logs
        path: |
          deletion_output.log
          api_calls.log