name: Tweet Deletion

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC daily
  workflow_dispatch:      # Allows manual trigger

jobs:
  delete-tweets:
    runs-on: ubuntu-latest
    
    env:
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specific version
        cache: 'pip'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-dev \
          build-essential \
          libffi-dev \
          libssl-dev \
          libjpeg-dev \
          zlib1g-dev \
          gcc \
          g++ \
          make

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade \
          setuptools \
          wheel \
          Cython \
          build

    - name: Install aiohttp separately
      run: |
        pip install --no-binary :all: aiohttp

    - name: Install other dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tweet deletion script
      run: python main.py 